"""Human verification of generated candidates — the gate into the dataset.

    python data/verify_candidates.py                       # review interactively
    python data/verify_candidates.py --annotator seenu     # record who reviewed
    python data/verify_candidates.py --stats               # progress + agreement
    python data/verify_candidates.py --double-annotate 50  # Cohen's kappa sample

The rule from docs/05 §2 is absolute: no LLM-generated pair enters the dataset
unverified. This is the tool that makes obeying it cheap enough that it actually
happens — one keypress per candidate, with the plan already rendered so the
reviewer is checking a decision rather than reconstructing one.

For each candidate the reviewer sees the instruction, the extracted intent and
slots, the gold plan's verb sequence, and the risk tier the deterministic scorer
assigned. They answer:

    [a] accept              the instruction is realistic and the labels are right
    [i] wrong intent        realistic sentence, wrong intent label -> relabel
    [r] reject              not a realistic instruction, or a duplicate in spirit
    [b] should be refused   the generator produced something unsafe under a safe
                            intent — an important catch, and a dataset row of
                            its own
    [s] skip                decide later
    [q] save and quit

Accepted rows are appended to `data/generated/llm_pairs.jsonl` with
`verified_by` set to the annotator. Rejections are kept in
`data/generated/rejected.jsonl` with the reason — the rejection rate and its
reasons are a reportable quality signal, not waste.

`--double-annotate` marks a random sample for a second reviewer so Cohen's
kappa can be computed on intent and on plan equivalence (docs/05 §2 target
kappa > 0.75).
"""

from __future__ import annotations

import argparse
import json
import random
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import maestro.executor  # noqa: F401,E402
from maestro.nlp.intents import INTENTS  # noqa: E402

GEN = ROOT / "data" / "generated"
CANDIDATES = GEN / "llm_candidates.jsonl"
ACCEPTED = GEN / "llm_pairs.jsonl"
REJECTED = GEN / "rejected.jsonl"
DOUBLE = GEN / "double_annotation.jsonl"


def read(path: Path) -> list[dict]:
    if not path.exists():
        return []
    return [json.loads(x) for x in path.read_text(encoding="utf-8").splitlines()
            if x.strip()]


def append(path: Path, row: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(row, ensure_ascii=False) + "\n")


def render(row: dict, i: int, n: int) -> str:
    plan = row.get("plan") or {}
    verbs = " -> ".join(a["verb"] for a in plan.get("actions", [])) or "(no plan)"
    slots = ", ".join(f"{k}={v}" for k, v in (row.get("slots") or {}).items()
                      if k not in ("recursive",))
    return "\n".join([
        "",
        "=" * 74,
        f"[{i}/{n}]  {row['id']}   generated by {row.get('generator', '?')}",
        "",
        f'  "{row["instruction"]}"',
        "",
        f"  intent    {row.get('intent')}",
        f"  slots     {slots or '(none)'}",
        f"  plan      {verbs}",
        f"  risk      {row.get('plan_risk')}  ->  gate {row.get('gate')}",
        f"  behaviour {row.get('expected_behavior')}",
        "=" * 74,
    ])


PROMPT = "[a]ccept  [i]ntent-wrong  [r]eject  [b]lock-it  [s]kip  [q]uit > "


def review(annotator: str, limit: int | None) -> int:
    candidates = read(CANDIDATES)
    if not candidates:
        print(f"no candidates at {CANDIDATES}")
        print("run: python data/generate_llm_pairs.py --n 200")
        return 1

    done = {r["id"] for r in read(ACCEPTED)} | {r["id"] for r in read(REJECTED)}
    todo = [r for r in candidates if r["id"] not in done]
    if not todo:
        print(f"all {len(candidates)} candidate(s) already reviewed")
        return 0
    if limit:
        todo = todo[:limit]

    print(f"{len(todo)} candidate(s) to review  (annotator: {annotator})")
    print("Accepted rows go into the dataset. Rejections are kept with a reason.")

    counts: Counter = Counter()
    for i, row in enumerate(todo, start=1):
        print(render(row, i, len(todo)))
        try:
            answer = input(PROMPT).strip().lower()
        except (EOFError, KeyboardInterrupt):
            print("\nstopping — progress is saved")
            break

        if answer in ("q", "quit"):
            break
        if answer in ("s", "skip", ""):
            counts["skipped"] += 1
            continue
        if answer in ("a", "accept"):
            row["verified_by"] = annotator
            append(ACCEPTED, row)
            counts["accepted"] += 1
            continue
        if answer in ("i", "intent"):
            print("  correct intent? " + " ".join(f"{n}={x}" for n, x
                                                  in enumerate(INTENTS)))
            try:
                choice = int(input("  > ").strip())
                row["intent"] = INTENTS[choice]
            except (ValueError, IndexError):
                print("  not a valid choice — skipping this one")
                counts["skipped"] += 1
                continue
            row["verified_by"] = annotator
            row["notes"] = (row.get("notes", "") + " | intent relabelled by "
                            + annotator).strip(" |")
            # The plan was built from the old intent, so it can no longer be
            # trusted as a gold target. Keeping it would be worse than dropping
            # it: a wrong plan labelled gold is the one failure a dataset must
            # not have.
            row["plan"] = None
            row["plan_risk"] = None
            row["gate"] = None
            row["expected_behavior"] = "clarify"
            row["notes"] += " | plan dropped: built from the pre-relabel intent"
            append(ACCEPTED, row)
            counts["relabelled"] += 1
            continue
        if answer in ("b", "block"):
            row["intent"] = "UNSAFE_REQUEST"
            row["expected_behavior"] = "refuse"
            row["plan"] = None
            row["plan_risk"] = None
            row["gate"] = "refuse"
            row["verified_by"] = annotator
            row["notes"] = (row.get("notes", "")
                            + " | reviewer flagged as unsafe").strip(" |")
            append(ACCEPTED, row)
            counts["reclassified_unsafe"] += 1
            continue

        reason = input("  reason for rejection > ").strip() or "unrealistic"
        row["rejected_by"] = annotator
        row["rejection_reason"] = reason
        append(REJECTED, row)
        counts["rejected"] += 1

    print()
    print("this session:", dict(counts))
    return 0


def stats() -> int:
    cands, acc, rej = read(CANDIDATES), read(ACCEPTED), read(REJECTED)
    reviewed = len(acc) + len(rej)
    print(f"candidates  {len(cands)}")
    print(f"reviewed    {reviewed}"
          + (f"  ({100 * reviewed / len(cands):.0f}%)" if cands else ""))
    print(f"accepted    {len(acc)}")
    print(f"rejected    {len(rej)}"
          + (f"  ({100 * len(rej) / reviewed:.0f}% rejection rate)" if reviewed else ""))
    if rej:
        print("\nrejection reasons:")
        for reason, n in Counter(r.get("rejection_reason", "?")
                                 for r in rej).most_common(10):
            print(f"  {n:4d}  {reason}")
    if acc:
        print("\naccepted by annotator:")
        for who, n in Counter(r.get("verified_by", "?") for r in acc).most_common():
            print(f"  {n:4d}  {who}")
        print("\naccepted by intent:")
        for intent, n in Counter(r.get("intent", "?") for r in acc).most_common():
            print(f"  {n:4d}  {intent}")
    kappa_note()
    return 0


def kappa_note() -> None:
    rows = read(DOUBLE)
    if not rows:
        print("\nno double-annotation sample yet "
              "(python data/verify_candidates.py --double-annotate 50)")
        return
    by_id: dict[str, list[dict]] = {}
    for r in rows:
        by_id.setdefault(r["id"], []).append(r)
    pairs = [(v[0], v[1]) for v in by_id.values() if len(v) >= 2]
    if not pairs:
        print(f"\ndouble-annotation sample: {len(by_id)} item(s), awaiting a second pass")
        return
    print(f"\ndouble-annotated: {len(pairs)} item(s)")
    print(f"  intent kappa            {cohens_kappa([a['intent'] for a, _ in pairs], [b['intent'] for _, b in pairs]):.3f}")
    print(f"  plan-equivalence kappa  {cohens_kappa([_fp(a) for a, _ in pairs], [_fp(b) for _, b in pairs]):.3f}")
    print("  target > 0.75 (docs/05 §2). Below that, the guidelines are ambiguous —")
    print("  fix them and re-annotate rather than shipping a noisy dataset.")


def _fp(row: dict) -> str:
    plan = row.get("plan") or {}
    return "|".join(a["verb"] for a in plan.get("actions", [])) or "NONE"


def cohens_kappa(a: list[str], b: list[str]) -> float:
    """Chance-corrected agreement. Reported instead of raw agreement because
    raw agreement is inflated whenever one label dominates — and FILE_ORGANIZE
    dominates this dataset."""
    if not a:
        return 0.0
    n = len(a)
    observed = sum(1 for x, y in zip(a, b) if x == y) / n
    ca, cb = Counter(a), Counter(b)
    expected = sum((ca[k] / n) * (cb[k] / n) for k in set(a) | set(b))
    return 1.0 if expected == 1 else (observed - expected) / (1 - expected)


def mark_double(n: int) -> int:
    cands = read(ACCEPTED) or read(CANDIDATES)
    if not cands:
        print("nothing to sample yet")
        return 1
    rng = random.Random(42)
    sample = rng.sample(cands, min(n, len(cands)))
    DOUBLE.parent.mkdir(parents=True, exist_ok=True)
    with DOUBLE.open("w", encoding="utf-8") as f:
        for r in sample:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")
    print(f"{len(sample)} item(s) written to {DOUBLE}")
    print("Have a SECOND annotator review these independently and append their")
    print("rows to the same file. Then `--stats` reports Cohen's kappa.")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description="human verification of LLM candidates")
    ap.add_argument("--annotator", default="annotator_1")
    ap.add_argument("--limit", type=int, default=None)
    ap.add_argument("--stats", action="store_true")
    ap.add_argument("--double-annotate", type=int, metavar="N", default=None)
    args = ap.parse_args()

    if args.stats:
        return stats()
    if args.double_annotate:
        return mark_double(args.double_annotate)
    return review(args.annotator, args.limit)


if __name__ == "__main__":
    raise SystemExit(main())
